name: Create Pull Request to Main

on:
  push:
    branches:
      - '*'  # Trigger on any push to any branch except the main branch

jobs:
  create-pull-request:
    if: github.ref != 'refs/heads/main'  # Run this job only if the branch is not main
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Check out the repository's code

    - name: Create Pull Request
      id: create-pull-request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the built-in GITHUB_TOKEN
        commit-message: "Automated Pull Request - ${{ github.sha }}"
        branch: ${{ github.ref }}  # The branch that triggered the workflow
        base: main  # The base branch for the pull request
        title: "Automated Pull Request"
        body: |
          This is an automated pull request created by GitHub Actions.

    - name: Output Pull Request URL
      run: echo "Pull Request URL: ${{ steps.create-pull-request.outputs.pull-request-url }}"
