name: Compile Multi-Repo Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: self-hosted

    steps:
    

      # Check out the first additional repository
      - name: Checkout additional repository 1
        uses: actions/checkout@v2
        with:
          repository: sathish1223/arg_api
          path: arg_api  # Specify the path where the repository should be checked out

      # Check out the second additional repository
      - name: Checkout additional repository 2
        uses: actions/checkout@v2
        with:
          repository: sathish1223/arg2
          path: arg2  # Specify the path where the repository should be checked out

      # Compile code from the first repository
      - name: Compile code from arg_api
        run: |
          cd arg_api
          chmod +x my_py.py
          python3 my_py.py

      # Compile code from the second repository
      - name: Compile code from arg
        run: |
          cd arg2
          chmod +x test.sh
          ./test.sh
